# org레포지토리에서 fork해온 현 레포지토리를 최신상태로 fetch and merge하는 스크립트입니다.

name: Sync and merge upstream repository
on:
  workflow_dispatch:
  schedule: 
  - cron: "0 1,5,9 * * *"

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'big-choi'
          git config --global user.email 'bos3321@gmail.com'
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://github.com/Foodlier/zb-foodlier.git
          git fetch upstream
          git checkout master
          git merge -Xtheirs upstream/master
          git push origin master
          # etc
